# Notes 2023-02-22

## The numpy library

In [2]:
import numpy as np

In [79]:
#dir(np)

### np.array 

for creating array objects from a sequence

In [5]:
rhs = np.array([30, 18, 2])
rhs

array([30, 18,  2])

a nested list gives a two-dimensional structure

In [75]:
coefficient_matrix = np.array([[3, 0, 0], [1, 8, 0], [0, 4, -2]])
coefficient_matrix

array([[ 3,  0,  0],
       [ 1,  8,  0],
       [ 0,  4, -2]])

### The linear algebra subpackage

In [78]:
#dir(np.linalg)

We use np.linalg.inv for inverting a matrix

In [77]:
np.linalg.inv(coefficient_matrix)

array([[ 0.33333333,  0.        ,  0.        ],
       [-0.04166667,  0.125     ,  0.        ],
       [-0.08333333,  0.25      , -0.5       ]])

(latex typesetting)

$$ Ax = b \rightarrow x = A^{-1}b $$

Here we multiply both sides by the inverse to get the vector of unknowns

In [80]:
x = np.linalg.inv(coefficient_matrix) @ rhs
x

array([10.,  1.,  1.])

Many sequence-like datatypes support unpacking of its elements

In [81]:
a, b, c = x

In [82]:
a

10.0

In [83]:
b

1.0

In [84]:
c

1.0

alternative approach (recommended) is to `np.linalg.solve` the linear system of equations without explicitely inverting the full matrix - more efficient

In [85]:
x = np.linalg.solve(coefficient_matrix, rhs)
x

array([10.,  1.,  1.])

Answer to the problem in the [slide](https://bb1000.github.io/external_libraries/#9)

In [86]:
a + 3*b + c

14.0

as a scalar product

In [87]:
x @ np.array([1, 3, 1])

14.0

Note that normal multiplication sign works elementwise

In [88]:
x * x

array([100.,   1.,   1.])

In [89]:
x + x

array([20.,  2.,  2.])

In [90]:
x @ x

102.0

In [27]:
x.__matmul__(x)

102.0

Note: the user of @ here maps to the class `__matmul__` method, and is completely separate from the use with decorators, e.g. the @staticmethod in the class lab

## Example: matrix multiplication

In [29]:
import time
import numpy
n = 256
a = numpy.ones((n, n))
b = numpy.ones((n, n))
c = numpy.zeros((n, n))
t1 = time.time()
for i in range(n):
    for j in range(n):
        for k in range(n):
            c[i, j] += a[i, k]*b[k, j]
t2 = time.time()
print("Loop timing", t2-t1)

Loop timing 9.231455326080322


In [30]:
a

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [31]:
c

array([[256., 256., 256., ..., 256., 256., 256.],
       [256., 256., 256., ..., 256., 256., 256.],
       [256., 256., 256., ..., 256., 256., 256.],
       ...,
       [256., 256., 256., ..., 256., 256., 256.],
       [256., 256., 256., ..., 256., 256., 256.],
       [256., 256., 256., ..., 256., 256., 256.]])

In [32]:
t1 = time.time()
c = a @ b
t2 = time.time()
print(t2-t1)

0.0027856826782226562


In [33]:
time.time()

1677062223.4808705

There is a jupyter magic command to time the content of a cell `%%time`

In [91]:
%%time
c = a @ b

TypeError: unsupported operand type(s) for @: 'numpy.float64' and 'numpy.float64'

### Eigenvalues of a matrix

$$ AX_i = \lambda_i X_i $$

In [97]:
A = coefficient_matrix
A

array([[ 3,  0,  0],
       [ 1,  8,  0],
       [ 0,  4, -2]])

In [98]:
l, X = np.linalg.eig(A)
l

array([-2.,  8.,  3.])

The columns of $X$ contain the eigenvectors

In [100]:
X

array([[ 0.        ,  0.        ,  0.96873032],
       [ 0.        ,  0.92847669, -0.19374606],
       [ 1.        ,  0.37139068, -0.15499685]])

A multiplied with an eigenvector

In [106]:
A @ X[:, 0]

array([ 0.,  0., -2.])

results in the same vector scaled by its eigenvalue

In [107]:
X[:, 0] * l[0]

array([-0., -0., -2.])

### Example: Taylor expansion

Expande the function $f$ around expansion point $x_0$

$$ f(x) = f(x_0) + (x - x_0)f'(x_0) + \frac{1}{2}(x - x_0)^2 f''(x_0) ... $$

In [108]:
x = np.arange(0, 2*np.pi, .1)
x

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2])

In [109]:
fx = np.sin(x)
fx

array([ 0.        ,  0.09983342,  0.19866933,  0.29552021,  0.38941834,
        0.47942554,  0.56464247,  0.64421769,  0.71735609,  0.78332691,
        0.84147098,  0.89120736,  0.93203909,  0.96355819,  0.98544973,
        0.99749499,  0.9995736 ,  0.99166481,  0.97384763,  0.94630009,
        0.90929743,  0.86320937,  0.8084964 ,  0.74570521,  0.67546318,
        0.59847214,  0.51550137,  0.42737988,  0.33498815,  0.23924933,
        0.14112001,  0.04158066, -0.05837414, -0.15774569, -0.2555411 ,
       -0.35078323, -0.44252044, -0.52983614, -0.61185789, -0.68776616,
       -0.7568025 , -0.81827711, -0.87157577, -0.91616594, -0.95160207,
       -0.97753012, -0.993691  , -0.99992326, -0.99616461, -0.98245261,
       -0.95892427, -0.92581468, -0.88345466, -0.83226744, -0.77276449,
       -0.70554033, -0.63126664, -0.55068554, -0.46460218, -0.37387666,
       -0.2794155 , -0.1821625 , -0.0830894 ])

In [110]:
x_0  = 5 
 # our expansion point

f0 = np.sin(x_0)
f0

-0.9589242746631385

In [111]:
f1 = (x - x_0)*np.cos(x_0)
f1

array([-1.41831093, -1.38994471, -1.36157849, -1.33321227, -1.30484605,
       -1.27647983, -1.24811362, -1.2197474 , -1.19138118, -1.16301496,
       -1.13464874, -1.10628252, -1.0779163 , -1.04955009, -1.02118387,
       -0.99281765, -0.96445143, -0.93608521, -0.90771899, -0.87935277,
       -0.85098656, -0.82262034, -0.79425412, -0.7658879 , -0.73752168,
       -0.70915546, -0.68078925, -0.65242303, -0.62405681, -0.59569059,
       -0.56732437, -0.53895815, -0.51059193, -0.48222572, -0.4538595 ,
       -0.42549328, -0.39712706, -0.36876084, -0.34039462, -0.3120284 ,
       -0.28366219, -0.25529597, -0.22692975, -0.19856353, -0.17019731,
       -0.14183109, -0.11346487, -0.08509866, -0.05673244, -0.02836622,
        0.        ,  0.02836622,  0.05673244,  0.08509866,  0.11346487,
        0.14183109,  0.17019731,  0.19856353,  0.22692975,  0.25529597,
        0.28366219,  0.3120284 ,  0.34039462])

In [112]:
f0 + f1

array([-2.3772352 , -2.34886898, -2.32050276, -2.29213655, -2.26377033,
       -2.23540411, -2.20703789, -2.17867167, -2.15030545, -2.12193924,
       -2.09357302, -2.0652068 , -2.03684058, -2.00847436, -1.98010814,
       -1.95174192, -1.92337571, -1.89500949, -1.86664327, -1.83827705,
       -1.80991083, -1.78154461, -1.75317839, -1.72481218, -1.69644596,
       -1.66807974, -1.63971352, -1.6113473 , -1.58298108, -1.55461486,
       -1.52624865, -1.49788243, -1.46951621, -1.44114999, -1.41278377,
       -1.38441755, -1.35605133, -1.32768512, -1.2993189 , -1.27095268,
       -1.24258646, -1.21422024, -1.18585402, -1.1574878 , -1.12912159,
       -1.10075537, -1.07238915, -1.04402293, -1.01565671, -0.98729049,
       -0.95892427, -0.93055806, -0.90219184, -0.87382562, -0.8454594 ,
       -0.81709318, -0.78872696, -0.76036074, -0.73199453, -0.70362831,
       -0.67526209, -0.64689587, -0.61852965])

*to be continued*